spring:
  application.name: ess-server
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate:
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
