package pl.papuda.ess.client.pages;

import pl.papuda.ess.client.components.AppPanel;

/**
 *
 * @author konrad
 */
public class ForgotPasswordPage extends AppPanel {

    /**
     * Creates new form ForgotPasswordPage
     */
    public ForgotPasswordPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForgotPassword = new javax.swing.JPanel();
        lblForgotPassword = new javax.swing.JLabel();
        lblForgotPasswordBody = new javax.swing.JLabel();
        lblForgotPasswordUsername = new javax.swing.JLabel();
        iptForgotPasswordUsername = new javax.swing.JTextField();
        lblForgotPasswordEmail = new javax.swing.JLabel();
        iptForgotPasswordEmail = new javax.swing.JTextField();
        btnForgotPasswordNext = new javax.swing.JButton();
        lblPromptLogIn2 = new javax.swing.JLabel();
        btnShowLogIn2 = new javax.swing.JButton();
        lblForgotPasswordError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        pnlForgotPassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlForgotPassword.setMinimumSize(new java.awt.Dimension(400, 500));
        pnlForgotPassword.setName(""); // NOI18N

        lblForgotPassword.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgotPassword.setText("Password Recovery");

        lblForgotPasswordBody.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgotPasswordBody.setText("Please enter your account details to proceed.");

        lblForgotPasswordUsername.setText("Username");

        lblForgotPasswordEmail.setText("Email address");

        btnForgotPasswordNext.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btnForgotPasswordNext.setText("NEXT");
        btnForgotPasswordNext.setToolTipText("");

        lblPromptLogIn2.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        lblPromptLogIn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptLogIn2.setText("Wrong page?");

        btnShowLogIn2.setText("GO BACK");
        btnShowLogIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLogIn2ActionPerformed(evt);
            }
        });

        lblForgotPasswordError.setForeground(new java.awt.Color(255, 51, 51));
        lblForgotPasswordError.setToolTipText("");

        javax.swing.GroupLayout pnlForgotPasswordLayout = new javax.swing.GroupLayout(pnlForgotPassword);
        pnlForgotPassword.setLayout(pnlForgotPasswordLayout);
        pnlForgotPasswordLayout.setHorizontalGroup(
            pnlForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForgotPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iptForgotPasswordEmail)
                    .addComponent(btnForgotPasswordNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblForgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblForgotPasswordBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iptForgotPasswordUsername)
                    .addComponent(lblPromptLogIn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowLogIn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblForgotPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlForgotPasswordLayout.createSequentialGroup()
                        .addGroup(pnlForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForgotPasswordUsername)
                            .addComponent(lblForgotPasswordEmail))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlForgotPasswordLayout.setVerticalGroup(
            pnlForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlForgotPasswordLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPasswordBody)
                .addGap(56, 56, 56)
                .addComponent(lblForgotPasswordUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iptForgotPasswordUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblForgotPasswordEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iptForgotPasswordEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForgotPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForgotPasswordNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPromptLogIn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowLogIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowLogIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLogIn2ActionPerformed
        switchPage("logIn");
    }//GEN-LAST:event_btnShowLogIn2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPasswordNext;
    private javax.swing.JButton btnShowLogIn2;
    private javax.swing.JTextField iptForgotPasswordEmail;
    private javax.swing.JTextField iptForgotPasswordUsername;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblForgotPasswordBody;
    private javax.swing.JLabel lblForgotPasswordEmail;
    private javax.swing.JLabel lblForgotPasswordError;
    private javax.swing.JLabel lblForgotPasswordUsername;
    private javax.swing.JLabel lblPromptLogIn2;
    private javax.swing.JPanel pnlForgotPassword;
    // End of variables declaration//GEN-END:variables
}
