package pl.papuda.ess.client.pages;

import com.fasterxml.jackson.core.type.TypeReference;
import java.io.IOException;
import java.net.http.HttpResponse;

import pl.papuda.ess.client.components.AppPanel;
import pl.papuda.ess.client.components.home.EventsList;
import pl.papuda.ess.client.components.home.UsersList;
import pl.papuda.ess.client.components.home.calendar.CalendarCustom;
import pl.papuda.ess.client.tools.Web;
import pl.papuda.ess.client.model.User;

public class HomePage extends AppPanel {
    
    private static final int NUM_HOME_TABS = 2;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    public void getUserPermissions() {
        HttpResponse<String> response;
        try {
            response = Web.sendGetRequest("/private/permissions");
        } catch (IOException | InterruptedException ex) {
            Web.unsetAccessToken();
            switchPage("logIn");
            return;
        }
        Web.user = Web.readResponseBody(response, new TypeReference<User>() {
        });
        String role = Web.user.getRole();
        if (role.equals("ADMIN")) {
            addUsersList();
        } else {
            System.out.println("User permissions: " + Web.user);
        }
        lblUsernameInfo.setText(Web.user.getUsername() + " (" + role + ")");
        eventsList1.updateUserPermissions(role);
    }

    public EventsList getEventsList() {
        return eventsList1;
    }

    public CalendarCustom getCalendarCustom() {
        return calendarCustom1;
    }

    private void addUsersList() {
        UsersList usersList = new UsersList();
        tabViewMenu.addTab("Users", usersList);
    }

    private void logOut() {
        switchPage("logIn");
        Web.unsetAccessToken(true);
        if (tabViewMenu.getTabCount() > NUM_HOME_TABS) {
            tabViewMenu.remove(NUM_HOME_TABS);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        tabViewMenu = new javax.swing.JTabbedPane();
        eventsList1 = new pl.papuda.ess.client.components.home.EventsList();
        settings1 = new pl.papuda.ess.client.components.home.settings.Settings();
        lblUsernameInfo = new javax.swing.JLabel();
        lblLoggedInAs = new javax.swing.JLabel();
        calendarCustom1 = new pl.papuda.ess.client.components.home.calendar.CalendarCustom();

        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pnlHome.setBackground(new java.awt.Color(0, 102, 102));
        pnlHome.setMinimumSize(new java.awt.Dimension(800, 500));

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        tabViewMenu.addTab("Events", eventsList1);
        tabViewMenu.addTab("Settings", settings1);

        lblUsernameInfo.setForeground(new java.awt.Color(204, 204, 204));
        lblUsernameInfo.setText("loading...");

        lblLoggedInAs.setForeground(new java.awt.Color(204, 204, 204));
        lblLoggedInAs.setText("Logged in as:");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLoggedInAs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsernameInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogOut))
                    .addComponent(tabViewMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogOut)
                            .addComponent(lblUsernameInfo)
                            .addComponent(lblLoggedInAs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabViewMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(calendarCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(pnlHome);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        logOut();
    }//GEN-LAST:event_btnLogOutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private pl.papuda.ess.client.components.home.calendar.CalendarCustom calendarCustom1;
    private pl.papuda.ess.client.components.home.EventsList eventsList1;
    private javax.swing.JLabel lblLoggedInAs;
    private javax.swing.JLabel lblUsernameInfo;
    private javax.swing.JPanel pnlHome;
    private pl.papuda.ess.client.components.home.settings.Settings settings1;
    private javax.swing.JTabbedPane tabViewMenu;
    // End of variables declaration//GEN-END:variables
}
