package pl.papuda.ess.client.pages;

import java.util.HashMap;
import java.util.Map;

import pl.papuda.ess.client.MainWindow;
import pl.papuda.ess.client.components.AppPanel;
import pl.papuda.ess.client.model.error.LoginException;
import pl.papuda.ess.client.model.body.LoginResponse;

/**
 *
 * @author konrad
 */
public class LogInPage extends AppPanel {

    /**
     * Creates new form LogInPage
     */
    public LogInPage() {
        initComponents();
    }

    public void setError(String message) {
        if (message.length() > 0) {
            System.err.println("Log in error: " + message);
        }
        lblLogInError.setText(message);
    }

    private void sendLogInRequest(Map<String, String> body) {
        MainWindow mainWindow = getMainWindow();
        LoginResponse response;
        try {
            response = mainWindow.logIn("/auth/login", body);
        } catch (LoginException ex) {
            String message = ex.getMessage();
            if (message.contains("email address is not verified")) {
                String email = message.split("'", 3)[1];
                mainWindow.verifyEmail(email);
            } else {
                setError(message);
            }
            return;
        } finally {
            btnLogIn.setEnabled(true);
        }
        System.out.println("Logged in as user #" + response.getUserId().toString());
        mainWindow.afterLoginVerified(response.getToken(), cbxRememberPassword.isSelected());
    }

    private void logIn() {
        setError("");
        btnLogIn.setEnabled(false);
        Map<String, String> body = new HashMap<>();
        body.put("username", iptLogInUsername.getText());
        body.put("password", new String(iptLogInPassword.getPassword()));
        new Thread(() -> sendLogInRequest(body)).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogIn = new javax.swing.JPanel();
        lblLogInHeader = new javax.swing.JLabel();
        lblLogInBody = new javax.swing.JLabel();
        lblLogInUsername = new javax.swing.JLabel();
        iptLogInUsername = new javax.swing.JTextField();
        lblLogInPassword = new javax.swing.JLabel();
        iptLogInPassword = new javax.swing.JPasswordField();
        cbxRememberPassword = new javax.swing.JCheckBox();
        btnForgotPassword = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        lblPromptSignUp = new javax.swing.JLabel();
        btnShowSignUp = new javax.swing.JButton();
        lblLogInError = new javax.swing.JLabel();

        pnlLogIn.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogIn.setMinimumSize(new java.awt.Dimension(400, 500));

        lblLogInHeader.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblLogInHeader.setForeground(new java.awt.Color(51, 51, 51));
        lblLogInHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogInHeader.setText("Log In");

        lblLogInBody.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogInBody.setText("Welcome to ESS! Please sign in.");

        lblLogInUsername.setText("Username");

        lblLogInPassword.setText("Password");

        cbxRememberPassword.setSelected(true);
        cbxRememberPassword.setText("Remember me");

        btnForgotPassword.setText("Forgot password?");
        btnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotPasswordActionPerformed(evt);
            }
        });

        btnLogIn.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btnLogIn.setText("LOG IN");
        btnLogIn.setToolTipText("");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        lblPromptSignUp.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        lblPromptSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptSignUp.setText("Don't have an account?");

        btnShowSignUp.setText("SIGN UP");
        btnShowSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSignUpActionPerformed(evt);
            }
        });

        lblLogInError.setForeground(new java.awt.Color(255, 51, 51));
        lblLogInError.setToolTipText("");

        javax.swing.GroupLayout pnlLogInLayout = new javax.swing.GroupLayout(pnlLogIn);
        pnlLogIn.setLayout(pnlLogInLayout);
        pnlLogInLayout.setHorizontalGroup(
                pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLogInHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLogInBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iptLogInUsername)
                                        .addComponent(iptLogInPassword)
                                        .addComponent(lblPromptSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnShowSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLogInError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlLogInLayout.createSequentialGroup()
                                                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblLogInUsername)
                                                        .addComponent(lblLogInPassword))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pnlLogInLayout.createSequentialGroup()
                                                .addComponent(cbxRememberPassword)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnForgotPassword)))
                                .addContainerGap())
        );
        pnlLogInLayout.setVerticalGroup(
                pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLogInLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblLogInHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogInBody)
                                .addGap(56, 56, 56)
                                .addComponent(lblLogInUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptLogInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLogInPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptLogInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbxRememberPassword)
                                        .addComponent(btnForgotPassword))
                                .addGap(18, 18, 18)
                                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogInError)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(lblPromptSignUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(pnlLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 418, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(pnlLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotPasswordActionPerformed
        switchPage("forgotPassword");
    }//GEN-LAST:event_btnForgotPasswordActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        logIn();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnShowSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSignUpActionPerformed
        switchPage("signUp");
    }//GEN-LAST:event_btnShowSignUpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPassword;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnShowSignUp;
    private javax.swing.JCheckBox cbxRememberPassword;
    private javax.swing.JPasswordField iptLogInPassword;
    private javax.swing.JTextField iptLogInUsername;
    private javax.swing.JLabel lblLogInBody;
    private javax.swing.JLabel lblLogInError;
    private javax.swing.JLabel lblLogInHeader;
    private javax.swing.JLabel lblLogInPassword;
    private javax.swing.JLabel lblLogInUsername;
    private javax.swing.JLabel lblPromptSignUp;
    private javax.swing.JPanel pnlLogIn;
    // End of variables declaration//GEN-END:variables
}
