package pl.papuda.ess.client.pages;

import java.util.HashMap;
import java.util.Map;
import java.util.regex.Pattern;

import pl.papuda.ess.client.MainWindow;
import pl.papuda.ess.client.components.AppPanel;
import pl.papuda.ess.client.model.error.LoginException;
import pl.papuda.ess.client.model.body.LoginResponse;

/**
 *
 * @author konrad
 */
public class SignUpPage extends AppPanel {

    private final Pattern passwordPattern = Pattern.compile("^(?=.*[A-Z])(?=.*[#?!@$ %^&*-]).{8,}$");
    private final Pattern emailPattern = Pattern.compile("^[^@]+@[^@]+$");

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    public void setError(String message) {
        if (message.length() > 0) {
            System.err.println("Sign up error: " + message);
        }
        lblSignUpError.setText(message);
    }

    public void signUp() {
        String email = iptSignUpEmail.getText();
        if (!emailPattern.matcher(email).matches()) {
            setError("Invalid email address");
            return;
        }
        String password = new String(iptSignUpPassword.getPassword());
        if (password.length() < 8) {
            setError("Password must be at least 8 characters long");
            return;
        }
        if (!passwordPattern.matcher(password).matches()) {
            setError("Password must have special and capital chars");
            return;
        }
        if (!password.equals(new String(iptSignUpPassword2.getPassword()))) {
            setError("Passwords do not match");
            return;
        }
        String username = iptSignUpUsername.getText();
        if (username.length() == 0) {
            setError("Username cannot be empty");
        }
        setError("");
        btnSignUp.setEnabled(false);
        Map<String, String> body = new HashMap<>();
        body.put("username", username);
        body.put("password", password);
        body.put("email", email);
        MainWindow mainWindow = getMainWindow();
        new Thread(() -> {
            LoginResponse response;
            try {
                response = mainWindow.logIn("/auth/register", body);
            } catch (LoginException ex) {
                String message = ex.getMessage();
                setError(message);
                return;
            } finally {
                btnSignUp.setEnabled(true);
            }
            mainWindow.afterLogin(response.getToken(), true);
            System.out.println("Successfully created user #" + response.getUserId().toString());
            mainWindow.verifyEmail(email);
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSignUp = new javax.swing.JPanel();
        lblSignUpHeader = new javax.swing.JLabel();
        lblSignUpDescription = new javax.swing.JLabel();
        lblSignUpEmail = new javax.swing.JLabel();
        iptSignUpEmail = new javax.swing.JTextField();
        lblSignUpUsername = new javax.swing.JLabel();
        iptSignUpUsername = new javax.swing.JTextField();
        lblSignUpPassword = new javax.swing.JLabel();
        iptSignUpPassword = new javax.swing.JPasswordField();
        lblSignUpPassword2 = new javax.swing.JLabel();
        iptSignUpPassword2 = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        lblPromptLogIn = new javax.swing.JLabel();
        btnShowLogIn = new javax.swing.JButton();
        lblSignUpError = new javax.swing.JLabel();

        pnlSignUp.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignUp.setMinimumSize(new java.awt.Dimension(400, 500));
        pnlSignUp.setName(""); // NOI18N

        lblSignUpHeader.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        lblSignUpHeader.setForeground(new java.awt.Color(51, 51, 51));
        lblSignUpHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUpHeader.setText("Sign Up");

        lblSignUpDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUpDescription.setText("Welcome to ESS! Please create an account.");

        lblSignUpEmail.setText("Email address");

        lblSignUpUsername.setText("Username (used for login and display)");

        lblSignUpPassword.setText("Password");

        lblSignUpPassword2.setText("Repeat password");

        btnSignUp.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btnSignUp.setText("SIGN UP");
        btnSignUp.setToolTipText("");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblPromptLogIn.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        lblPromptLogIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPromptLogIn.setText("Already have an account?");

        btnShowLogIn.setText("LOG IN");
        btnShowLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLogInActionPerformed(evt);
            }
        });

        lblSignUpError.setForeground(new java.awt.Color(255, 51, 51));
        lblSignUpError.setToolTipText("");

        javax.swing.GroupLayout pnlSignUpLayout = new javax.swing.GroupLayout(pnlSignUp);
        pnlSignUp.setLayout(pnlSignUpLayout);
        pnlSignUpLayout.setHorizontalGroup(
                pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlSignUpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSignUpPassword2)
                                        .addComponent(lblSignUpPassword)
                                        .addComponent(lblSignUpEmail)
                                        .addComponent(lblSignUpUsername)
                                        .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSignUpHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSignUpDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iptSignUpPassword)
                                        .addGroup(pnlSignUpLayout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(lblPromptLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(btnShowLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iptSignUpPassword2)
                                        .addComponent(iptSignUpEmail)
                                        .addComponent(iptSignUpUsername)
                                        .addComponent(lblSignUpError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pnlSignUpLayout.setVerticalGroup(
                pnlSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlSignUpLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblSignUpHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSignUpDescription)
                                .addGap(18, 18, 18)
                                .addComponent(lblSignUpEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptSignUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSignUpPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblSignUpPassword2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptSignUpPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSignUpUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSignUpError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPromptLogIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(pnlSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 492, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(pnlSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        signUp();
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnShowLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLogInActionPerformed
        switchPage("logIn");
    }//GEN-LAST:event_btnShowLogInActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowLogIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JTextField iptSignUpEmail;
    private javax.swing.JPasswordField iptSignUpPassword;
    private javax.swing.JPasswordField iptSignUpPassword2;
    private javax.swing.JTextField iptSignUpUsername;
    private javax.swing.JLabel lblPromptLogIn;
    private javax.swing.JLabel lblSignUpDescription;
    private javax.swing.JLabel lblSignUpEmail;
    private javax.swing.JLabel lblSignUpError;
    private javax.swing.JLabel lblSignUpHeader;
    private javax.swing.JLabel lblSignUpPassword;
    private javax.swing.JLabel lblSignUpPassword2;
    private javax.swing.JLabel lblSignUpUsername;
    private javax.swing.JPanel pnlSignUp;
    // End of variables declaration//GEN-END:variables
}
