package pl.papuda.ess.client.components.home;

import java.io.IOException;
import java.net.http.HttpResponse;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import pl.papuda.ess.client.tools.Web;
import pl.papuda.ess.client.model.User;

/**
 *
 * @author konrad
 */
public class UserListItem extends javax.swing.JPanel {

    User user;

    /**
     * Creates new form UserListItem
     *
     * @param user the user to initialise the card with
     */
    public UserListItem(User user) {
        this.user = user;
        initComponents();
        initFields();
    }

    private void initFields() {
        iptUserEmail.setText(user.getEmail());
        lblUserUuid.setText(user.getId().toString());
        lblUsername.setText(user.getUsername());
        String role = user.getRole();
        JRadioButton radioButton = switch (role) {
            case "USER" -> rdbUserRoleUser;
            case "STAFF" -> rdbUserRoleStaff;
            case "ADMIN" -> rdbUserRoleAdmin;
            default -> null;
        };
        if (radioButton == null) {
            System.err.println("Unknown user type: " + role);
        } else {
            radioButton.setSelected(true);
        }
    }

    private String getButtonGroupSelectedText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private void setButtonGroupSelectedText(ButtonGroup buttonGroup, String text, boolean ignoreCase) throws RuntimeException {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            String buttonText = button.getText();
            boolean equals = ignoreCase
                    ? buttonText.equalsIgnoreCase(text)
                    : buttonText.equals(text);
            if (equals) {
                button.setSelected(true);
                return;
            }
            button.setSelected(false);
        }
        System.err.println("No button group child contained given text: " + text);
    }

    private String getUserRole() {
        String text = getButtonGroupSelectedText(rbgUserRole);
        if (text == null) {
            System.err.println("No user role radio button is checked.");
            return "USER";
        }
        return text.toUpperCase();
    }

    private void saveUser() {
        HttpResponse<String> response;
        String id = user.getId().toString();
        String email = iptUserEmail.getText();
        String role = getUserRole();
        String body = "{\"email\":\"" + email + "\",\"role\":\"" + role + "\"}";
        try {
            response = Web.sendPutRequest("/admin/user/" + id, body);
        } catch (IOException | InterruptedException ex) {
            System.err.println("Error occurred while updating user");
            return;
        } finally {
            btnUpdateUser.setEnabled(true);
        }
        int status = response.statusCode();
        if (status == 200) {
            user.setEmail(email);
            user.setRole(role);
            return;
        }
        System.err.println("Non-OK status code updating user: " + status);
        setButtonGroupSelectedText(rbgUserRole, user.getRole(), true);
        iptUserEmail.setText(user.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgUserRole = new javax.swing.ButtonGroup();
        lblUsername = new javax.swing.JLabel();
        lblUsernameEmailSeparator = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        lblUserUuid = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();
        iptUserEmail = new javax.swing.JTextField();
        rdbUserRoleUser = new javax.swing.JRadioButton();
        rdbUserRoleStaff = new javax.swing.JRadioButton();
        rdbUserRoleAdmin = new javax.swing.JRadioButton();
        btnUpdateUser = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUsername.setText("someuser");

        lblUsernameEmailSeparator.setForeground(new java.awt.Color(132, 132, 132));
        lblUsernameEmailSeparator.setText("•");

        lblUserEmail.setText("Email");

        lblUserUuid.setText("7");

        lblUserRole.setText("Role");

        iptUserEmail.setText("test@email.com");

        rbgUserRole.add(rdbUserRoleUser);
        rdbUserRoleUser.setText("User");

        rbgUserRole.add(rdbUserRoleStaff);
        rdbUserRoleStaff.setText("Staff");

        rbgUserRole.add(rdbUserRoleAdmin);
        rdbUserRoleAdmin.setText("Admin");

        btnUpdateUser.setText("Update");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(iptUserEmail)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdbUserRoleUser)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdbUserRoleStaff)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdbUserRoleAdmin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                                                .addComponent(btnUpdateUser))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblUserRole)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblUserUuid)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblUsernameEmailSeparator)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblUsernameEmailSeparator)
                                        .addComponent(lblUserUuid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUserEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iptUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUserRole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdbUserRoleUser)
                                        .addComponent(rdbUserRoleStaff)
                                        .addComponent(rdbUserRoleAdmin)
                                        .addComponent(btnUpdateUser))
                                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        btnUpdateUser.setEnabled(false);
        new Thread(this::saveUser).start();
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JTextField iptUserEmail;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JLabel lblUserUuid;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsernameEmailSeparator;
    private javax.swing.ButtonGroup rbgUserRole;
    private javax.swing.JRadioButton rdbUserRoleAdmin;
    private javax.swing.JRadioButton rdbUserRoleStaff;
    private javax.swing.JRadioButton rdbUserRoleUser;
    // End of variables declaration//GEN-END:variables
}
