package pl.papuda.ess.client.budgetTracker;

import pl.papuda.ess.client.model.Event;

public class BudgetTracker extends javax.swing.JPanel {

    Event event = null;

    public void setEvent(Event e) {
        event = e;
        budgetPie2.setEvent(e);
    }

    /**
     * Creates new form BudgetTracker
     */
    public BudgetTracker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        budgetPie2 = new pl.papuda.ess.client.budgetTracker.BudgetPie();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(budgetPie2, javax.swing.GroupLayout.PREFERRED_SIZE, 487,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(467, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(budgetPie2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pl.papuda.ess.client.budgetTracker.BudgetPie budgetPie2;
    // End of variables declaration//GEN-END:variables
}
