/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pl.papuda.ess.client.budgetTracker;

import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.Date;
import pl.papuda.ess.client.Time;

public class ExpenseForm extends javax.swing.JPanel {

    /**
     * Creates new form ExpenseForm
     */
    public ExpenseForm() {
        initComponents();
        setCurrentDatetime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblExpenseTitle = new javax.swing.JLabel();
        iptExpenseTitle = new javax.swing.JTextField();
        lblExpenseCost = new javax.swing.JLabel();
        iptExpenseCost = new javax.swing.JFormattedTextField();
        lblExpenseDate = new javax.swing.JLabel();
        iptExpenseDate = new javax.swing.JFormattedTextField();
        iptExpenseTime = new javax.swing.JFormattedTextField();
        lblExpenseTime = new javax.swing.JLabel();
        cbxExpenseNow = new javax.swing.JCheckBox();

        jLabel1.setText("Add a new expense");

        lblExpenseTitle.setText("Expense title");

        lblExpenseCost.setText("Expense cost");

        lblExpenseDate.setText("Expense date (dd/MM/y)");

        iptExpenseDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        iptExpenseDate.setEnabled(false);

        iptExpenseTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        iptExpenseTime.setEnabled(false);

        lblExpenseTime.setText("Expense time (HH:mm)");

        cbxExpenseNow.setSelected(true);
        cbxExpenseNow.setText("Use current date and time");
        cbxExpenseNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxExpenseNowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iptExpenseTitle)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iptExpenseCost)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExpenseDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblExpenseTime, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addComponent(lblExpenseTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExpenseCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxExpenseNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iptExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iptExpenseTime)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExpenseTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iptExpenseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblExpenseCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iptExpenseCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxExpenseNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpenseDate)
                    .addComponent(lblExpenseTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iptExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iptExpenseTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setCurrentDatetime() {
        LocalDateTime dateTime = LocalDateTime.now();
        Date date = Date.from(dateTime.toInstant(Time.zoneOffset));
        iptExpenseDate.setValue(date);
        iptExpenseTime.setValue(date);
    }
    
    private LocalDateTime getExpenseDate() throws Exception {
        try {
            return LocalDateTime.parse(iptExpenseDate.getText() + "T" + iptExpenseTime.getText(), Time.dateTimeFormat);
        } catch (DateTimeParseException ex) {
            throw new Exception("Invalid expense date or time");
        }
    }
    
    private void cbxExpenseNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxExpenseNowActionPerformed
        boolean useCustomDatetime = !cbxExpenseNow.isSelected();
        iptExpenseDate.setEnabled(useCustomDatetime);
        iptExpenseTime.setEnabled(useCustomDatetime);
        if (useCustomDatetime) {
            return;
        }
        setCurrentDatetime();
    }//GEN-LAST:event_cbxExpenseNowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxExpenseNow;
    private javax.swing.JFormattedTextField iptExpenseCost;
    private javax.swing.JFormattedTextField iptExpenseDate;
    private javax.swing.JFormattedTextField iptExpenseTime;
    private javax.swing.JTextField iptExpenseTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblExpenseCost;
    private javax.swing.JLabel lblExpenseDate;
    private javax.swing.JLabel lblExpenseTime;
    private javax.swing.JLabel lblExpenseTitle;
    // End of variables declaration//GEN-END:variables
}
