package pl.papuda.ess.client;

import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import pl.papuda.ess.client.model.Event;

public class CalendarCustom extends javax.swing.JPanel {

    private int month;
    private int year;
    private Event[] events = null;
    
    /**
     * Creates new form Calendar
     */
    public CalendarCustom() {
        initComponents();
        resetCalendar();
    }
    
    private void resetCalendar() {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        month = calendar.get(Calendar.MONTH);
        year = calendar.get(Calendar.YEAR);
        scrollCalendar();
    }
    
    public void updateCalendar(Event[] events) {
        this.events = events;
        update();
    }
    
    private void update() {
        pnlCalendarContainer.removeAll();
        pnlCalendarContainer.add(new CalendarPanel(month, year, events), BorderLayout.CENTER);
    }
    
    private void scrollCalendar() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, month);
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DATE, 1);
        SimpleDateFormat df  = new SimpleDateFormat("MMMM yyyy");
        lblCalendarInfo.setText(df.format(calendar.getTime()));
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCalendarContainer = new javax.swing.JPanel();
        pnlCalendarButtons = new javax.swing.JPanel();
        btnCalendarLeft = new javax.swing.JButton();
        btnCalendarRight = new javax.swing.JButton();
        lblCalendarInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlCalendarContainer.setLayout(new java.awt.BorderLayout());

        pnlCalendarButtons.setBackground(new java.awt.Color(102, 102, 102));

        btnCalendarLeft.setBackground(new java.awt.Color(153, 153, 153));
        btnCalendarLeft.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        btnCalendarLeft.setForeground(new java.awt.Color(153, 153, 153));
        btnCalendarLeft.setText("‹");
        btnCalendarLeft.setBorder(null);
        btnCalendarLeft.setContentAreaFilled(false);
        btnCalendarLeft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalendarLeft.setFocusPainted(false);
        btnCalendarLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarLeftActionPerformed(evt);
            }
        });

        btnCalendarRight.setBackground(new java.awt.Color(102, 102, 102));
        btnCalendarRight.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        btnCalendarRight.setForeground(new java.awt.Color(153, 153, 153));
        btnCalendarRight.setText("›");
        btnCalendarRight.setBorder(null);
        btnCalendarRight.setContentAreaFilled(false);
        btnCalendarRight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalendarRight.setFocusPainted(false);
        btnCalendarRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarRightActionPerformed(evt);
            }
        });

        lblCalendarInfo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCalendarInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblCalendarInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalendarInfo.setText("October 2024");

        javax.swing.GroupLayout pnlCalendarButtonsLayout = new javax.swing.GroupLayout(pnlCalendarButtons);
        pnlCalendarButtons.setLayout(pnlCalendarButtonsLayout);
        pnlCalendarButtonsLayout.setHorizontalGroup(
            pnlCalendarButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalendarButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalendarLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCalendarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalendarRight)
                .addContainerGap())
        );
        pnlCalendarButtonsLayout.setVerticalGroup(
            pnlCalendarButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalendarButtonsLayout.createSequentialGroup()
                .addGroup(pnlCalendarButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCalendarRight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalendarLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(pnlCalendarButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalendarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCalendarContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlCalendarButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlCalendarButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCalendarContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalendarLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarLeftActionPerformed
        if (month == 0) {
            month = 11;
            year--;
        } else {
            month--;
        }
        scrollCalendar();
    }//GEN-LAST:event_btnCalendarLeftActionPerformed

    private void btnCalendarRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarRightActionPerformed
        if (month == 11) {
            month = 0;
            year++;
        } else {
            month++;
        }
        scrollCalendar();
    }//GEN-LAST:event_btnCalendarRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendarLeft;
    private javax.swing.JButton btnCalendarRight;
    private javax.swing.JLabel lblCalendarInfo;
    private javax.swing.JPanel pnlCalendarButtons;
    private javax.swing.JPanel pnlCalendarContainer;
    // End of variables declaration//GEN-END:variables
}
