# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ESS server Azure Web App - event-scheduling-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      # Needed for Spring Boot configuration, which requires database connection details at build time
      - name: Save the database secrets to /server/application.properties
        run: touch application.properties;
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> application.properties;
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> application.properties;
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> application.properties;

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "${{ github.workspace }}/server/target/*.jar"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "event-scheduling-system"
          slot-name: "Production"
          package: "*.jar"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E281F9F7439E491994BAB31AA2C80D5D }}

